kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: stage-product-detail-api
spec:
  hosts:
  - stageproductdetailapi.trendyol.com
  http:
    route:
    - destination:
        host: stage-product-detail-api
        subset: stage